use_frameworks!

platform :ios, '8.0'

target 'DQPageController_Example' do
    
  pod 'DQPageController', :path => '../'
#  pod 'YYKit', '~> 1.0.9'

  target 'DQPageController_Tests' do
    inherit! :search_paths

  end

end
